# Generated by Django 4.1.6 on 2023-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fullname', models.CharField(max_length=128)),
                ('profession', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('work_experience', models.IntegerField()),
                ('raiting', models.FloatField()),
            ],
        ),
    ]
